### ISSUE TITLE
Torch dependency

### ISSUE THREAD

**Issue by TParcollet** [earthspecies/alp-data#15]
Just to mention that any mac running on Intel CPU will not be able to install torch 2.6. The version needs to get down to 2.2 for it to work. I somehow suspect that quite a few people work on old Macs :p

**Comment by GaganNarula** [comment]
@mil-ad I think we need to think about torch as a dependency. If we want to include things like canonical ways to do audio resampling, audio streaming etc (which I'm not sure belongs in esp-data), then we might want to include both torch>=2.0.0 and torchaudio (corresponding to the torch version). If we don't care about these, then I suggest removing torch altogether from deps.

**Comment by mil-ad** [comment]
@TParcollet could you include the error you're getting? We should change `pyproject.toml` (and maybe even the template repo?) to include torch indexes for mac to work. See uv's post here: https://docs.astral.sh/uv/guides/integration/pytorch/

This is what we do in naturelm:

```toml
[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "platform_system == 'Darwin'" },
  { index = "pytorch-cu118", marker = "platform_system == 'Linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "platform_system == 'Darwin'" },
  { index = "pytorch-cu118", marker = "platform_system == 'Linux'" },
]
torchaudio = [
  { index = "pytorch-cpu", marker = "platform_system == 'Darwin'" },
  { index = "pytorch-cu118", marker = "platform_system == 'Linux'" },
]
```
